matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11.3

sudo: required

language: cpp

addons:
  apt:
    sources:
    - xenial
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main'
    - sourceline: 'ppa:mhier/libboost-latest'
    packages:
    - gcc
    - g++
    - libjsoncpp-dev
    - uuid-dev
    - zlib1g-dev
    - postgresql-server-dev-10
    - openssl
    - libssl-dev
    - libsqlite3-dev
    - build-essential
    - cmake
    - boost1.67
  homebrew:
    packages:
    - jsoncpp
    - ossp-uuid
    - openssl
    - cmake
    - libtool
    - lz4
    - mariadb
    - sqlite3
    update: true
before_install:
  - wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - tar xf release-1.10.0.tar.gz
  - cd googletest-release-1.10.0
  - cmake .
  - make
  - sudo make install
  - cd -
before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
       brew tap homebrew/services;
       brew services restart postgresql; 
       sleep 2;
       psql -c 'create user postgres superuser;' postgres; 
    fi

services:
  - postgresql
script:
  - ./build.sh -t && ./test.sh -t
