name: build 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build: 
    name: build-linux
    runs-on: ubuntu-latest
    container: nxxm/nxxm-ubuntu
    env:
      NXXM_AUTH: ${ secrets.NXXM_AUTH }
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: nxxm builds project 
        run: |
          export HOME=/root
          nxxm . -t linux --dont-upgrade --verbose --test all 
